### PR TITLE
Added a few missing SAL defines.

### PR DESCRIPTION
**Pull request by bkaradzic**

### CODE REVIEW

**Comment by nemequ** [comment]
Awesome, thanks!

It looks like some of those macros are from the obsolete declspec-based version, which I didn't include in Salieri. I don't see a reason not to include them (as well as the other declspec-based macros), though.

I'm not sure how I missed those other macros, but thanks for noticing and fixing it ☺.

I just pushed a version which should include all the annotations from the declspec-based version to a wip/v2 branch, which includes your patch. I need to do some testing but I'll try to get a new version out ASAP.

If you're using `__in_ecount`/`__in_ecount_opt` in new code you might want to consider switching to `_In_count_`/`_In_opt_count_` (per https://cloudblogs.microsoft.com/microsoftsecure/2009/06/11/a-declspec-sal-to-attribute-sal-rosetta-stone/)

**Comment by bkaradzic** [comment]
I'm not using it, but rather some MS headers (Direct3D 9, 11, 12) that I build with MinGW are using it.

I just switched my old method to salieri since it seems better, here are all macros I found before:
https://github.com/bkaradzic/bx/commit/8a64ea7abb4e2c92dae953e8eaa8c23fd61ab938#diff-2751f603724a7c04d42e09d409c2b5d4

**Comment by nemequ** [comment]
That's very helpful, thanks. I'll try to go through that list this afternoon and verify Salieri has everything.

**Comment by bkaradzic** [comment]
Also few more here: https://github.com/bkaradzic/bgfx/blob/25476fc8a20f2f2fa77b6aa4d11dfe1c7dd00df7/3rdparty/dxsdk/include/d3dcommon.h#L58

Do you use something to generate this header or edit it manually?

**Comment by nemequ** [comment]
For the ones I just did (the declspec ones) I copied and pasted the list from https://msdn.microsoft.com/en-us/library/windows/desktop/aa383701(v=vs.85).aspx then threw together a quick regex in emacs to add in the boilerplate. I probably did something similar using the lists linked to from https://msdn.microsoft.com/en-us/library/ms182032.aspx for the attribute-based ones, but TBH I don't really remember.

I'm a bit hesitant about grepping the headers from VS for macro names then automatically generating the boilerplate based on that, since it would bring Salieri much closer to being a derivative work… I think what I'll do is grep the VS headers and Salieri, diff the list, then manually insert any missing macros. I just need some time to install a Windows VM and VS.

**Pull request closed without merging**
